[package]
name = "clak-gui"
version = "0.3.2"
edition = "2021"

[dependencies]
clak-engine = { path = "../engine" }
clak-diagnostics = { path = "../diagnostics" }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
arboard = "3"
slint = { version = "1.9", default-features = false, features = ["backend-winit", "renderer-skia-opengl", "compat-1-2", "accessibility"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[build-dependencies]
slint-build = "1.9"

[profile.dev]
debug = 1

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
panic = "abort"
strip = true
